export interface Product {
  id: string;
  name: string;
  shortName?: string;
  description: string;
  shortDescription?: string;
  category: 'ai-agent' | 'cloud-applications';
  href: string;
  icon?: string; // Professional icon names: 'users', 'workflow', 'search', 'banknote', 'bot', 'building', 'chart', 'brain', 'shield'
  featured?: boolean;
  status: 'live' | 'coming-soon' | 'beta';
  tags?: string[];
  image?: string;
  productUrl?: string;
  // New fields for header organization
  headerCategory?: 'erp' | 'hcm' | 'cx' | 'scm' | 'data-intelligence' | 'marketplace';
  showInHeader?: boolean;
  headerOrder?: number; // Order within the category
}

export const AI_AGENT_PRODUCTS: Product[] = [
  {
    id: 'hr',
    name: 'AI HR Agent',
    shortName: 'HR',
    description: 'AI-First HRMS Platform that replaces traditional HR systems with intelligent automation. Cut administrative workload by 80% while delivering exceptional employee experiences with AI resume screening, document knowledge chat, AI-based leave management, and automated payroll processing.',
    shortDescription: 'AI-First HRMS Platform with intelligent automation',
    category: 'ai-agent',
    href: '/product/hr',
    icon: 'users',
    featured: true,
    status: 'live',
    tags: ['AI', 'HR', 'HRMS', 'Automation', 'Employee Management', 'Payroll', 'Leave Management'],
    image: '/products/hr/01.png',
    productUrl: 'https://hr.augment.cfd/'
  },
  {
    id: 'flow',
    name: 'Augment Flow',
    shortName: 'Flow',
    description: 'AI Agent that works even when you\'re away. Your words become actions across every platform you use. 200+ apps working towards a future where technology acts, not just responds.',
    shortDescription: 'AI-powered workflow automation across 200+ apps',
    category: 'ai-agent',
    href: '/product/flow',
    icon: 'workflow',
    featured: true,
    status: 'live',
    tags: ['Workflow Automation', 'AI Agent', 'Integration', 'Productivity'],
    image: '/products/flow/01.png',
    productUrl: 'https://flow.augment.cfd/'
  },
  {
    id: 'searchai',
    name: 'AI-Powered Search Engine',
    shortName: 'SearchAI',
    description: 'A powerful AI-powered search engine with intelligent generative UI for deep research. Get natural language responses with interactive components, multiple AI model support, and advanced search capabilities.',
    shortDescription: 'AI-powered search engine for intelligent research',
    category: 'ai-agent',
    href: '/product/searchai',
    icon: 'search',
    featured: true,
    status: 'live',
    tags: ['AI Search', 'Research', 'Natural Language', 'Deep Search'],
    image: '/products/searchai/01.png',
    productUrl: 'https://searchai.augment.cfd/'
  },
  {
    id: 'finance-ai',
    name: 'AI Financial Intelligence',
    shortName: 'FinAI',
    description: 'Transform your financial life with AI-powered insights, automated receipt scanning, and intelligent budget management. Your personal finance assistant that never sleeps.',
    shortDescription: 'AI-powered personal finance management platform',
    category: 'ai-agent',
    href: '/product/finance-ai',
    icon: 'banknote',
    featured: true,
    status: 'live',
    tags: ['Finance', 'Budgeting', 'Receipt Scanning', 'AI Insights'],
    image: '/products/finance-ai/01.png',
    productUrl: 'https://financeai.augment.cfd/'
  },
  {
    id: 'resume-ai',
    name: 'AI Resume & Career Assistant',
    shortName: 'Resume AI',
    description: 'Transform any job description into a perfectly tailored, ATS-optimized resume in seconds. Our AI analyzes job requirements and crafts compelling content that gets you noticed.',
    shortDescription: 'AI-powered resume builder with ATS optimization',
    category: 'ai-agent',
    href: '/product/resume-ai',
    icon: 'users',
    featured: true,
    status: 'live',
    tags: ['Resume', 'ATS Optimization', 'Job Search', 'Career'],
    image: '/products/resume-ai/01.png',
    productUrl: 'https://resumeai.augment.cfd/'
  },
  {
    id: 'health-ai',
    name: 'AI Health & Wellness Platform',
    shortName: 'Health AI',
    description: 'AI-powered health intelligence platform that tracks symptoms, analyzes patterns, and provides personalized health insights on autopilot for hours.',
    shortDescription: 'AI-powered health intelligence and tracking',
    category: 'ai-agent',
    href: '/product/health-ai',
    icon: 'heart',
    featured: true,
    status: 'live',
    tags: ['Health', 'AI Assistant', 'Tracking', 'Analytics', 'Medication'],
    image: '/products/health-ai/01.png',
    productUrl: 'https://healthai.augment.cfd/'
  },
  {
    id: 'ai-security-auditor',
    name: 'CyberGuard Enterprise',
    shortName: 'CyberGuard',
    description: 'Enterprise-grade autonomous security orchestration platform that continuously monitors, analyzes, and protects your infrastructure with intelligent threat detection and automated compliance reporting.',
    shortDescription: 'Autonomous security orchestration and threat intelligence',
    category: 'ai-agent',
    href: '/product/ai-security-auditor',
    icon: 'shield',
    featured: true,
    status: 'live',
    tags: ['Security Orchestration', 'Threat Intelligence', 'Compliance Automation', 'Enterprise Security'],
    image: '/products/ai-security-auditor/01.png',
    productUrl: '/docs/ai-security-auditor'
  },
  {
    id: 'ai-cloud-architect',
    name: 'CloudArchitect Pro',
    shortName: 'CloudArchitect',
    description: 'Intelligent infrastructure automation platform that automatically designs, deploys, and optimizes enterprise cloud architectures with predictive scaling and cost intelligence.',
    shortDescription: 'Intelligent infrastructure automation and optimization',
    category: 'ai-agent',
    href: '/product/ai-cloud-architect',
    icon: 'building',
    featured: true,
    status: 'live',
    tags: ['Infrastructure Automation', 'Cloud Architecture', 'Predictive Scaling', 'Cost Intelligence'],
    image: '/products/ai-cloud-architect/01.png',
    productUrl: '/docs/ai-cloud-architect'
  },
  {
    id: 'ai-cost-optimizer',
    name: 'FinOps Intelligence',
    shortName: 'FinOps',
    description: 'Advanced financial operations platform that uses machine learning to automatically optimize cloud spend, predict cost trends, and maximize ROI across multi-cloud environments.',
    shortDescription: 'Advanced financial operations and cost intelligence',
    category: 'ai-agent',
    href: '/product/ai-cost-optimizer',
    icon: 'chart',
    featured: true,
    status: 'live',
    tags: ['FinOps', 'Cost Intelligence', 'ROI Optimization', 'Cloud Economics'],
    image: '/products/ai-cost-optimizer/01.png',
    productUrl: '/docs/ai-cost-optimizer'
  },
  {
    id: 'ai-workflow-builder',
    name: 'Process Automation Engine',
    shortName: 'ProcessEngine',
    description: 'Enterprise workflow orchestration platform that autonomously designs, executes, and optimizes complex business processes with natural language understanding and intelligent decision automation.',
    shortDescription: 'Enterprise workflow orchestration and process automation',
    category: 'ai-agent',
    href: '/product/ai-workflow-builder',
    icon: 'workflow',
    featured: true,
    status: 'live',
    tags: ['Workflow Orchestration', 'Process Automation', 'Decision Intelligence', 'Business Process Management'],
    image: '/products/ai-workflow-builder/01.png',
    productUrl: '/docs/ai-workflow-builder'
  },
  {
    id: 'app-security-scan',
    name: 'Threat Surface Intelligence',
    shortName: 'ThreatSurface',
    description: 'Advanced attack surface management platform that continuously discovers, assesses, and prioritizes security vulnerabilities across your entire digital ecosystem with predictive risk analytics.',
    shortDescription: 'Attack surface management and predictive risk analytics',
    category: 'ai-agent',
    href: '/product/app-security-scan',
    icon: 'shield',
    featured: true,
    status: 'live',
    tags: ['Attack Surface Management', 'Risk Analytics', 'Vulnerability Intelligence', 'Security Assessment'],
    image: '/products/app-security-scan/01.png',
    productUrl: '/docs/ai-vuln-scanner'
  },
  {
    id: 'log-insight',
    name: 'Observability Intelligence',
    shortName: 'ObservabilityIQ',
    description: 'Enterprise observability platform that transforms massive log datasets into actionable intelligence with predictive anomaly detection and automated incident correlation.',
    shortDescription: 'Enterprise observability and predictive analytics',
    category: 'ai-agent',
    href: '/product/log-insight',
    icon: 'chart',
    featured: true,
    status: 'live',
    tags: ['Observability', 'Predictive Analytics', 'Incident Intelligence', 'Log Analytics'],
    image: '/products/log-insight/01.png',
    productUrl: '/docs/ai-log-analyzer'
  },
  {
    id: 'policy-compliance',
    name: 'Governance Automation Suite',
    shortName: 'GovernanceAuto',
    description: 'Enterprise governance platform that autonomously manages policies, ensures compliance, and enforces security standards across your infrastructure with intelligent risk assessment.',
    shortDescription: 'Enterprise governance automation and compliance intelligence',
    category: 'ai-agent',
    href: '/product/policy-compliance',
    icon: 'shield',
    featured: true,
    status: 'live',
    tags: ['Governance Automation', 'Compliance Intelligence', 'Policy Management', 'Risk Assessment'],
    image: '/products/policy-compliance/01.png',
    productUrl: '/docs/ai-policy-advisor'
  },
  {
    id: 'security-collector',
    name: 'Cyber Threat Intelligence',
    shortName: 'CyberThreat',
    description: 'Advanced threat hunting platform that proactively identifies, analyzes, and neutralizes sophisticated cyber threats using behavioral analytics and threat intelligence automation.',
    shortDescription: 'Advanced threat hunting and behavioral analytics',
    category: 'ai-agent',
    href: '/product/security-collector',
    icon: 'shield',
    featured: true,
    status: 'live',
    tags: ['Threat Hunting', 'Behavioral Analytics', 'Threat Intelligence', 'Cyber Defense'],
    image: '/products/security-collector/01.png',
    productUrl: '/docs/ai-threat-hunter'
  },
  {
    id: 'cloud-governance',
    name: 'Multi-Cloud Operations',
    shortName: 'MultiCloudOps',
    description: 'Enterprise multi-cloud optimization platform that automatically tunes performance, orchestrates resources, and maximizes efficiency across hybrid cloud environments with predictive scaling.',
    shortDescription: 'Multi-cloud operations and performance optimization',
    category: 'ai-agent',
    href: '/product/cloud-governance',
    icon: 'building',
    featured: true,
    status: 'live',
    tags: ['Multi-Cloud Operations', 'Performance Optimization', 'Resource Orchestration', 'Hybrid Cloud'],
    image: '/products/cloud-governance/01.png',
    productUrl: '/docs/ai-cloud-optimizer'
  },
  {
    id: 'devops-conductor',
    name: 'DevOps Acceleration Platform',
    shortName: 'DevOpsAccel',
    description: 'Enterprise development acceleration platform that autonomously optimizes code quality, automates testing pipelines, and accelerates delivery with intelligent development analytics.',
    shortDescription: 'Development acceleration and intelligent DevOps automation',
    category: 'ai-agent',
    href: '/product/devops-conductor',
    icon: 'bot',
    featured: true,
    status: 'live',
    tags: ['DevOps Acceleration', 'Code Intelligence', 'Pipeline Automation', 'Development Analytics'],
    image: '/products/devops-conductor/01.png',
    productUrl: '/docs/ai-dev-assistant'
  },
  {
    id: 'monitoring-quickstart',
    name: 'Infrastructure Intelligence',
    shortName: 'InfraIntel',
    description: 'Enterprise infrastructure monitoring platform that predicts system failures, optimizes performance, and provides actionable intelligence with autonomous remediation capabilities.',
    shortDescription: 'Infrastructure intelligence and autonomous monitoring',
    category: 'ai-agent',
    href: '/product/monitoring-quickstart',
    icon: 'chart',
    featured: true,
    status: 'live',
    tags: ['Infrastructure Intelligence', 'Predictive Monitoring', 'Autonomous Remediation', 'Performance Analytics'],
    image: '/products/monitoring-quickstart/01.png',
    productUrl: '/docs/ai-monitor-iq'
  },
  {
    id: 'net-router',
    name: 'Network Operations Center',
    shortName: 'NetworkOps',
    description: 'Self-optimizing network operations platform that autonomously manages traffic patterns, reduces latency, and maximizes network performance with intelligent routing algorithms.',
    shortDescription: 'Autonomous network operations and intelligent routing',
    category: 'ai-agent',
    href: '/product/net-router',
    icon: 'workflow',
    featured: true,
    status: 'live',
    tags: ['Network Operations', 'Intelligent Routing', 'Traffic Optimization', 'Network Intelligence'],
    image: '/products/net-router/01.png',
    productUrl: '/docs/ai-network-optimizer'
  },
  {
    id: 'integration-automation',
    name: 'Data Pipeline Orchestrator',
    shortName: 'DataOrchestrator',
    description: 'Enterprise data pipeline platform that autonomously designs, monitors, and optimizes data workflows with intelligent performance tuning and predictive error recovery.',
    shortDescription: 'Enterprise data pipeline orchestration and optimization',
    category: 'ai-agent',
    href: '/product/integration-automation',
    icon: 'chart',
    featured: true,
    status: 'live',
    tags: ['Data Pipeline', 'Workflow Orchestration', 'Performance Intelligence', 'Data Operations'],
    image: '/products/integration-automation/01.png',
    productUrl: '/docs/ai-data-flow'
  },
  {
    id: 'cloud-bridge',
    name: 'Integration Automation Hub',
    shortName: 'IntegrationHub',
    description: 'Enterprise integration platform that autonomously discovers patterns, orchestrates API connections, and optimizes data flow with intelligent mapping and transformation automation.',
    shortDescription: 'Enterprise integration automation and orchestration',
    category: 'ai-agent',
    href: '/product/cloud-bridge',
    icon: 'workflow',
    featured: true,
    status: 'live',
    tags: ['Integration Automation', 'API Orchestration', 'Pattern Intelligence', 'Data Transformation'],
    image: '/products/cloud-bridge/01.png',
    productUrl: '/docs/ai-integration-master'
  },
  {
    id: 'neuroflow-orchestrator',
    name: 'NeuroFlow Orchestrator',
    shortName: 'NeuroFlow',
    description: 'AI-native orchestration platform powered by neural networks that intelligently manages workflows, predicts resource needs, and adapts execution patterns for optimal performance.',
    shortDescription: 'Neural network-powered workflow orchestration',
    category: 'ai-agent',
    href: '/product/neuroflow-orchestrator',
    icon: 'brain',
    featured: true,
    status: 'live',
    tags: ['Neural Orchestration', 'Workflow Management', 'Predictive Scaling', 'AI Automation'],
    image: '/products/neuroflow-orchestrator/01.png',
    productUrl: '/docs/neuroflow-orchestrator'
  },
  {
    id: 'aether-cli',
    name: 'Aether CLI',
    shortName: 'Aether',
    description: 'Intelligent command-line automation tool that understands natural language, learns from your patterns, and provides context-aware assistance for complex operations.',
    shortDescription: 'AI-powered command-line automation and assistance',
    category: 'ai-agent',
    href: '/product/aether-cli',
    icon: 'bot',
    featured: true,
    status: 'live',
    tags: ['CLI Automation', 'Natural Language Processing', 'Context Awareness', 'Developer Tools'],
    image: '/products/aether-cli/01.png',
    productUrl: '/docs/aether-cli'
  },
  {
    id: 'augmentos',
    name: 'AugmentOS',
    shortName: 'AugmentOS',
    description: 'Enterprise-grade AI-powered browser that transforms your workflow with intelligent automation. Just describe your task in plain language — it handles all the clicking, typing, and navigating for you. A privacy-first alternative to Chrome, built for the AI era.',
    shortDescription: 'Enterprise AI Browser with intelligent automation',
    category: 'ai-agent',
    href: '/product/augmentos',
    icon: 'bot',
    featured: true,
    status: 'live',
    tags: ['AI Browser', 'Automation', 'Privacy', 'Enterprise', 'Workflow', 'Natural Language'],
    image: '/products/augmentos/01.png',
    productUrl: 'https://augmentos.augment.cfd/'
  },
  {
    id: 'agentforge',
    name: 'AgentForge',
    shortName: 'AgentForge',
    description: 'No-code AI automation platform with smart agents. Build AI agents that can think and act across 431 tools, customizable, and secure platform for enterprise automation workflows.',
    shortDescription: 'AI Agents & Automation Platform with 431+ integrations',
    category: 'ai-agent',
    href: '/product/agentforge',
    icon: 'workflow',
    featured: true,
    status: 'live',
    tags: ['AI Agents', 'No-Code', 'Automation', 'Open Source', 'Enterprise', 'Workflow', 'Integrations'],
    image: '/products/agentforge/01.png',
    productUrl: 'https://agentforge.augment.cfd/'
  },
  {
    id: 'synapse-sdk',
    name: 'Synapse SDK',
    shortName: 'Synapse',
    description: 'Adaptive AI automation SDK that embeds neural network capabilities into applications, enabling self-optimizing features and intelligent decision-making at scale.',
    shortDescription: 'Adaptive AI automation SDK with neural network integration',
    category: 'ai-agent',
    href: '/product/synapse-sdk',
    icon: 'brain',
    featured: true,
    status: 'live',
    tags: ['AI SDK', 'Neural Networks', 'Adaptive Automation', 'Intelligent Applications'],
    image: '/products/synapse-sdk/01.png',
    productUrl: '/docs/synapse-sdk'
  }
];
