export interface Product {
  id: string;
  name: string;
  shortName?: string;
  description: string;
  shortDescription?: string;
  category: 'ai-agent' | 'cloud-applications';
  href: string;
  icon?: string; // Professional icon names: 'users', 'workflow', 'search', 'banknote', 'bot', 'building', 'chart', 'brain', 'shield'
  featured?: boolean;
  status: 'live' | 'coming-soon' | 'beta';
  tags?: string[];
  image?: string;
  productUrl?: string;
  // New fields for header organization
  headerCategory?: 'erp' | 'hcm' | 'cx' | 'scm' | 'data-intelligence' | 'marketplace';
  showInHeader?: boolean;
  headerOrder?: number; // Order within the category
}

export const CLOUD_APP_PRODUCTS: Product[] = [
  // ===== ENTERPRISE RESOURCE PLANNING (ERP) =====
  {
    id: 'erp-overview',
    name: 'Applications Overview',
    shortName: 'Overview',
    description: 'Complete overview of all Enterprise Resource Planning applications and modules available in the Augment Cloud platform.',
    shortDescription: 'ERP applications overview and navigation hub',
    category: 'cloud-applications',
    href: '/product/erp',
    icon: 'building',
    featured: true,
    status: 'live',
    tags: ['ERP', 'Overview', 'Applications', 'Enterprise'],
    image: '/products/erp/01.png',
    productUrl: 'https://erp.augment.cfd/',
    headerCategory: 'erp',
    showInHeader: true,
    headerOrder: 1
  },
  {
    id: 'financial-management',
    name: 'Financial Management',
    shortName: 'Finance',
    description: 'Comprehensive financial management with general ledger, accounts payable/receivable, budgeting, financial reporting, and advanced analytics for complete financial control.',
    shortDescription: 'Complete financial management and accounting solution',
    category: 'cloud-applications',
    href: '/product/accounting',
    icon: 'banknote',
    featured: true,
    status: 'live',
    tags: ['Accounting', 'Finance', 'General Ledger', 'Financial Reporting', 'Budgeting'],
    image: '/products/accounting/01.png',
    productUrl: 'https://erp.augment.cfd/app/accounting',
    headerCategory: 'erp',
    showInHeader: true,
    headerOrder: 2
  },
  {
    id: 'procurement',
    name: 'Procurement',
    shortName: 'Procurement',
    description: 'Streamlined procurement process with supplier management, purchase analytics, RFQ process, and automated purchase workflows. Complete purchasing control and vendor management.',
    shortDescription: 'Complete procurement and supplier management',
    category: 'cloud-applications',
    href: '/product/purchasing',
    icon: 'shopping-cart',
    featured: true,
    status: 'live',
    tags: ['Purchasing', 'Procurement', 'Suppliers', 'RFQ', 'Vendor Management'],
    image: '/products/purchasing/01.png',
    productUrl: 'https://erp.augment.cfd/app/buying',
    headerCategory: 'erp',
    showInHeader: true,
    headerOrder: 3
  },
  {
    id: 'project-management',
    name: 'Project Management',
    shortName: 'Projects',
    description: 'Enterprise project management with resource allocation, project planning, time tracking, milestone management, and team collaboration tools for successful project delivery.',
    shortDescription: 'Enterprise project tracking and team collaboration',
    category: 'cloud-applications',
    href: '/product/projects',
    icon: 'folder',
    featured: true,
    status: 'live',
    tags: ['Projects', 'Task Management', 'Time Tracking', 'Collaboration', 'Planning'],
    image: '/products/projects/01.png',
    productUrl: 'https://erp.augment.cfd/app/projects',
    headerCategory: 'erp',
    showInHeader: true,
    headerOrder: 4
  },
  {
    id: 'risk-management',
    name: 'Risk Management and Compliance',
    shortName: 'Risk & Compliance',
    description: 'Enterprise risk assessment, compliance monitoring, audit trails, and regulatory reporting to ensure business continuity and regulatory adherence.',
    shortDescription: 'Enterprise risk assessment and compliance management',
    category: 'cloud-applications',
    href: '/product/risk-management',
    icon: 'shield',
    featured: true,
    status: 'coming-soon',
    tags: ['Risk Management', 'Compliance', 'Audit', 'Regulatory', 'Governance'],
    image: '/products/risk-management/01.png',
    productUrl: '/book-demo',
    headerCategory: 'erp',
    showInHeader: true,
    headerOrder: 5
  },
  {
    id: 'enterprise-performance',
    name: 'Enterprise Performance Management',
    shortName: 'Performance',
    description: 'Strategic planning, budgeting, forecasting, and performance analytics to drive business growth and operational excellence.',
    shortDescription: 'Strategic planning and performance analytics',
    category: 'cloud-applications',
    href: '/product/enterprise-performance',
    icon: 'trending-up',
    featured: true,
    status: 'coming-soon',
    tags: ['Performance Management', 'Strategic Planning', 'Budgeting', 'Analytics', 'KPIs'],
    image: '/products/enterprise-performance/01.png',
    productUrl: '/book-demo',
    headerCategory: 'erp',
    showInHeader: true,
    headerOrder: 6
  },

  // ===== SUPPLY CHAIN & MANUFACTURING (SCM) =====
  {
    id: 'supply-chain-planning',
    name: 'Supply Chain Planning',
    shortName: 'Supply Planning',
    description: 'Advanced supply chain planning with demand forecasting, supply planning, inventory optimization, and supplier collaboration for efficient operations.',
    shortDescription: 'Advanced supply chain planning and optimization',
    category: 'cloud-applications',
    href: '/product/supply-chain-planning',
    icon: 'truck',
    featured: true,
    status: 'coming-soon',
    tags: ['Supply Chain', 'Planning', 'Forecasting', 'Optimization', 'Logistics'],
    image: '/products/supply-chain/01.png',
    productUrl: '/book-demo',
    headerCategory: 'scm',
    showInHeader: true,
    headerOrder: 1
  },
  {
    id: 'inventory-management',
    name: 'Inventory Management',
    shortName: 'Inventory',
    description: 'Real-time stock tracking, warehouse management, and automated reorder points. Complete inventory control with barcode support, multi-location tracking, and inventory valuation.',
    shortDescription: 'Complete inventory and stock management solution',
    category: 'cloud-applications',
    href: '/product/inventory',
    icon: 'package',
    featured: true,
    status: 'live',
    tags: ['Inventory', 'Stock Management', 'Warehouse', 'Barcode', 'Asset Tracking'],
    image: '/products/inventory/01.png',
    productUrl: 'https://erp.augment.cfd/app/stock',
    headerCategory: 'scm',
    showInHeader: true,
    headerOrder: 2
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing',
    shortName: 'Manufacturing',
    description: 'End-to-end production planning, scheduling, and quality control. BOM management, work orders, production tracking, and quality assurance for efficient manufacturing operations.',
    shortDescription: 'Complete production planning and manufacturing control',
    category: 'cloud-applications',
    href: '/product/manufacturing',
    icon: 'settings',
    featured: true,
    status: 'live',
    tags: ['Manufacturing', 'Production', 'BOM', 'Quality Control', 'Work Orders'],
    image: '/products/manufacturing/01.png',
    productUrl: 'https://erp.augment.cfd/app/manufacturing',
    headerCategory: 'scm',
    showInHeader: true,
    headerOrder: 3
  },
  {
    id: 'maintenance',
    name: 'Maintenance',
    shortName: 'Maintenance',
    description: 'Preventive and predictive maintenance scheduling, asset lifecycle management, maintenance cost tracking, and equipment performance monitoring.',
    shortDescription: 'Complete maintenance and asset lifecycle management',
    category: 'cloud-applications',
    href: '/product/assets',
    icon: 'hard-drive',
    featured: true,
    status: 'live',
    tags: ['Assets', 'Maintenance', 'Lifecycle', 'Equipment', 'Preventive'],
    image: '/products/assets/01.png',
    productUrl: 'https://erp.augment.cfd/app/assets',
    headerCategory: 'scm',
    showInHeader: true,
    headerOrder: 4
  },
  {
    id: 'product-lifecycle',
    name: 'Product Lifecycle Management',
    shortName: 'PLM',
    description: 'Complete product lifecycle management from concept to retirement, including design collaboration, change management, and product data management.',
    shortDescription: 'Complete product lifecycle and design management',
    category: 'cloud-applications',
    href: '/product/plm',
    icon: 'layers',
    featured: true,
    status: 'coming-soon',
    tags: ['PLM', 'Product Design', 'Lifecycle', 'Collaboration', 'Change Management'],
    image: '/products/plm/01.png',
    productUrl: '/book-demo',
    headerCategory: 'scm',
    showInHeader: true,
    headerOrder: 5
  },

  // ===== HUMAN CAPITAL MANAGEMENT (HCM) =====
  {
    id: 'human-resources',
    name: 'Human Resources',
    shortName: 'HR Core',
    description: 'AI-powered cloud HRMS platform that replaces traditional HR systems with intelligent automation. Features AI resume screening, automated payroll processing, smart leave management, and 24/7 AI-powered employee support.',
    shortDescription: 'AI-powered cloud-based HR management system',
    category: 'cloud-applications',
    href: '/product/hr',
    icon: 'users',
    featured: true,
    status: 'live',
    tags: ['AI', 'Cloud HR', 'HRMS', 'Automation', 'Employee Management', 'AI Assistant'],
    image: '/products/hr/01.png',
    productUrl: 'https://hr.augment.cfd/',
    headerCategory: 'hcm',
    showInHeader: true,
    headerOrder: 1
  },
  {
    id: 'talent-management',
    name: 'Talent Management',
    shortName: 'Talent',
    description: 'Comprehensive talent acquisition, performance management, learning and development, succession planning, and career development for optimal workforce management.',
    shortDescription: 'Complete talent acquisition and development platform',
    category: 'cloud-applications',
    href: '/product/talent-management',
    icon: 'star',
    featured: true,
    status: 'coming-soon',
    tags: ['Talent Management', 'Recruitment', 'Performance', 'Learning', 'Development'],
    image: '/products/talent/01.png',
    productUrl: '/book-demo',
    headerCategory: 'hcm',
    showInHeader: true,
    headerOrder: 2
  },
  {
    id: 'workforce-management',
    name: 'Workforce Management',
    shortName: 'Workforce',
    description: 'Advanced workforce planning, scheduling, time and attendance tracking, labor cost management, and compliance monitoring for optimal workforce utilization.',
    shortDescription: 'Advanced workforce planning and scheduling solution',
    category: 'cloud-applications',
    href: '/product/workforce-management',
    icon: 'clock',
    featured: true,
    status: 'coming-soon',
    tags: ['Workforce', 'Scheduling', 'Time Tracking', 'Labor Management', 'Compliance'],
    image: '/products/workforce/01.png',
    productUrl: '/book-demo',
    headerCategory: 'hcm',
    showInHeader: true,
    headerOrder: 3
  },
  {
    id: 'payroll',
    name: 'Payroll',
    shortName: 'Payroll',
    description: 'Automated payroll processing, tax calculations, benefits administration, and compliance management. Complete payroll solution with employee self-service portal.',
    shortDescription: 'Complete payroll processing and compliance management',
    category: 'cloud-applications',
    href: '/product/payroll',
    icon: 'credit-card',
    featured: true,
    status: 'live',
    tags: ['Payroll', 'Tax Calculation', 'Benefits', 'Compliance', 'Employee Portal'],
    image: '/products/payroll/01.png',
    productUrl: 'https://erp.augment.cfd/app/payroll',
    headerCategory: 'hcm',
    showInHeader: true,
    headerOrder: 4
  },

  // ===== CUSTOMER EXPERIENCE (CX) =====
  {
    id: 'marketing',
    name: 'Marketing',
    shortName: 'Marketing',
    description: 'All-in-one marketing automation platform with email campaigns, social media management, lead nurturing, analytics, and customer journey mapping for exceptional customer experiences.',
    shortDescription: 'Complete marketing automation and campaign management',
    category: 'cloud-applications',
    href: '/product/marketing',
    icon: 'megaphone',
    featured: true,
    status: 'coming-soon',
    tags: ['Marketing', 'Automation', 'Email Campaigns', 'Analytics', 'Customer Journey'],
    image: '/products/marketing/01.png',
    productUrl: '/book-demo',
    headerCategory: 'cx',
    showInHeader: true,
    headerOrder: 1
  },
  {
    id: 'sales',
    name: 'Sales',
    shortName: 'Sales',
    description: 'Complete sales pipeline from lead generation to order fulfillment. Manage quotations, sales orders, customer portal, and sales analytics with integrated commission tracking.',
    shortDescription: 'Complete sales pipeline and order management',
    category: 'cloud-applications',
    href: '/product/sales',
    icon: 'trending-up',
    featured: true,
    status: 'live',
    tags: ['Sales', 'Pipeline', 'Orders', 'Quotations', 'Lead Management', 'CRM'],
    image: '/products/sales/01.png',
    productUrl: 'https://erp.augment.cfd/app/selling',
    headerCategory: 'cx',
    showInHeader: true,
    headerOrder: 2
  },
  {
    id: 'service',
    name: 'Service',
    shortName: 'Service',
    description: 'Advanced customer support platform with ticketing system, live chat, knowledge base, automation, and comprehensive analytics for superior customer service experiences.',
    shortDescription: 'Complete customer support and service solution',
    category: 'cloud-applications',
    href: '/product/customer-support',
    icon: 'headphones',
    featured: true,
    status: 'coming-soon',
    tags: ['Support', 'Service', 'Live Chat', 'Ticketing', 'Knowledge Base'],
    image: '/products/customer-support/01.png',
    productUrl: '/book-demo',
    headerCategory: 'cx',
    showInHeader: true,
    headerOrder: 3
  },

  // ===== FUSION DATA INTELLIGENCE PLATFORM =====
  {
    id: 'augment-suite',
    name: 'Augment Suite',
    shortName: 'Augment Suite',
    description: 'Unified business intelligence and analytics platform that connects all your business applications, providing real-time insights, predictive analytics, and AI-powered decision support.',
    shortDescription: 'Unified business intelligence and analytics platform',
    category: 'cloud-applications',
    href: '/product/augmentdb',
    icon: 'chart',
    featured: true,
    status: 'live',
    tags: ['Business Intelligence', 'Analytics', 'Data Platform', 'AI Insights', 'Reporting'],
    image: '/products/augmentdb/01.png',
    productUrl: '/documentation/augmentdb',
    headerCategory: 'data-intelligence',
    showInHeader: true,
    headerOrder: 1
  },

  // ===== AUGMENT MARKETPLACE =====
  {
    id: 'marketplace',
    name: 'Augment Marketplace',
    shortName: 'Marketplace',
    description: 'Discover and integrate third-party applications, extensions, and services that extend your Augment Cloud platform capabilities with pre-built integrations.',
    shortDescription: 'Third-party applications and integrations marketplace',
    category: 'cloud-applications',
    href: '/marketplace',
    icon: 'store',
    featured: true,
    status: 'coming-soon',
    tags: ['Marketplace', 'Integrations', 'Third-party', 'Extensions', 'Apps'],
    image: '/products/marketplace/01.png',
    productUrl: '/marketplace',
    headerCategory: 'marketplace',
    showInHeader: true,
    headerOrder: 1
  },

  // ===== ADDITIONAL APPLICATIONS (Not shown in header but available) =====
  {
    id: 'social-media',
    name: 'Social Media Management',
    shortName: 'Social Media',
    description: 'Comprehensive social media management platform for content creation, scheduling, engagement tracking, analytics, and multi-platform publishing.',
    shortDescription: 'Complete social media management and analytics platform',
    category: 'cloud-applications',
    href: '/product/social-media',
    icon: 'share',
    featured: true,
    status: 'coming-soon',
    tags: ['Social Media', 'Content Management', 'Analytics', 'Publishing'],
    image: '/products/social-media/01.png',
    productUrl: '/book-demo',
    showInHeader: false
  },
  {
    id: 'scheduling',
    name: 'Scheduling Platform',
    shortName: 'Scheduling',
    description: 'Advanced scheduling platform with calendar integration, availability management, automated booking, team coordination, and meeting analytics.',
    shortDescription: 'Complete scheduling and calendar management solution',
    category: 'cloud-applications',
    href: '/product/scheduling',
    icon: 'clock',
    featured: true,
    status: 'coming-soon',
    tags: ['Scheduling', 'Calendar', 'Meetings', 'Availability'],
    image: '/products/scheduling/01.gif',
    productUrl: '/book-demo',
    showInHeader: false
  }
];
